name: Deploy to IIS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release -o ./publish
        
        #      - name: dotnet publish 
        #        run: dotnet publish -c Release -o ./publish

      - name: Deploy to IIS
        shell: powershell
        run: |
               Start-Process powershell -Verb RunAs -ArgumentList "iisreset /stop"  
               Start-Sleep -Seconds 10 
               Start-Process xcopy -Verb RunAs -ArgumentList "/Y /S /I publish\* C:\inetpub\wwwroot\ServiceManagerApi\"
          #          xcopy /Y /S /I publish\* C:\inetpub\wwwroot\ServiceManagerApi\      
               Start-Process powershell -Verb RunAs -ArgumentList "iisreset /start"  