name: Deploy to IIS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Build
#        run: |
#          dotnet restore
#          dotnet build --configuration Release

      - name: Deploy
        run: |
          $ErrorActionPreference = 'Stop'
          $iisSiteName = 'SmWebApiPool'
          $websiteName = 'SmWebApi'
          $publishPath = 'C:\inetpub\wwwroot\ServiceManagerApi' 
          $iisAppPoolName = 'SmWebApiPool'
          $webconfig = 'web.config'
          $appsettings = 'appsettings.json'
          
      - name: Stop the website
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "Stop-WebAppPool -Name $iisSiteName"
          Start-Sleep -Seconds 10
        
          
#      - name: Remove the existing app from IIS
#        run: Start-Process powershell -Verb RunAs -ArgumentList 'Remove-WebApplication -Name $websiteName -Site $iisSiteName -ErrorAction Stop'
          
      - name: Delete the existing files from the website folder  
        run: Start-Process powershell -Verb RunAs -ArgumentList "Get-ChildItem -Path $publishPath -Exclude $webconfig, $appsettings -Recurse | Remove-Item -Recurse -Force"
        
      - name: Publish the app 
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "dotnet publish -o $publishPath"
          Start-Sleep -Seconds 10
      
      - name: Start the website
        run: Start-Process powershell -Verb RunAs -ArgumentList "Start-WebAppPool -Name $iisSiteName" 
