name: Deploy to IIS

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release -o ${{ env.DOTNET_ROOT }}\publish

      - name: Deploy to IIS
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "iisreset /stop"   
          Start-Sleep -Seconds 10
          xcopy /Y /S /I ${{ env.DOTNET_ROOT }}\publish\* C:\inetpub\wwwroot\ServiceManagerApi\
          Start-Process powershell -Verb RunAs -ArgumentList "iisreset /start"
        