name: Deploy to IIS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          dotnet restore
#          dotnet build --configuration Release

      - name: Deploy
        run: |
          $ErrorActionPreference = 'Stop'
          $iisSiteName = 'SmWebApiPool'
          $websiteName = 'SmWebApi'
          $publishPath = 'C:\inetpub\wwwroot\ServiceManagerApi' 
          $iisAppPoolName = 'SmWebApiPool'
          
      - name: Stop the website
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "Stop-WebAppPool -Name $iisSiteName"
          Start-Sleep -Seconds 10
        
          
#      - name: Remove the existing app from IIS
#        run: Start-Process powershell -Verb RunAs -ArgumentList 'Remove-WebApplication -Name $websiteName -Site $iisSiteName -ErrorAction Stop'
          
      - name: Delete the existing files from the website folder  
        run: Get-ChildItem "C:\inetpub\wwwroot\ServiceManagerApi" -Exclude 'web.config', 'appsettings.json' -Recurse | Remove-Item -Recurse -Force
        
      - name: Publish the app
#        run: dotnet publish -c Release -o $publishPath 
        run: | 
          dotnet publish -c Release -o "C:\inetpub\wwwroot\ServiceManagerApi"
          Start-Sleep -Seconds 10
      
      - name: Start the website
        run: Start-Process powershell -Verb RunAs -ArgumentList "Start-WebAppPool -Name $iisSiteName" 
