name: Deploy to IIS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Build with dotnet
        shell: cmd
        run: dotnet build --configuration Release
        
      - name: dotnet publish
        shell: cmd
        run: dotnet publish -c Release -o ./publish
        
      - name: Deploy to IIS
        shell: powershell 
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "iisreset /stop"  
          Start-Sleep -Seconds 10 
          Start-Process powershell -Verb RunAs -ArgumentList "iisreset /start"  
          
          
#          xcopy /Y /S /I publish\* C:\inetpub\wwwroot\ServiceManagerApi\ 
          
          
          
          
          
          
          
          
          
#          run as administrator
#          Start-Process powershell -Verb RunAs -ArgumentList "iisreset /start"










#      - name: Build
#        run: |
#          dotnet restore
#          dotnet build --configuration Release
#
#
#      - name: Stop the website
#        run: |
#          Start-Process powershell -Verb RunAs -ArgumentList "Stop-WebAppPool -Name SmWebApiPool"
#          Start-Sleep -Seconds 10
#          
#          
#          #      - name: Remove the existing app from IIS
#          #        run: Start-Process powershell -Verb RunAs -ArgumentList 'Remove-WebApplication -Name $websiteName -Site $iisSiteName -ErrorAction Stop'
#
#      - name: Delete the existing files from the website folder
#        #        run: Start-Process powershell -Verb RunAs -ArgumentList "Get-ChildItem $publishPath -Exclude $webconfig, $appsettings -Recurse | Remove-Item -Recurse -Force"
#        #        run: Start-Process powershell -Verb RunAs -ArgumentList "Remove-Item -Path $publishPath -Recurse -Force -ErrorAction Stop -Exclude $webconfig, $appsettings"
#        #        run: Start-Process powershell -Verb RunAs -ArgumentList "Remove-Item C:\inetpub\wwwroot\ServiceManagerApi\* -Recurse -Force -Exclude web.config"
#        run: Start-Process powershell -Verb RunAs -ArgumentList "get-childitem 'C:\inetpub\wwwroot\ServiceManagerApi\' -Exclude *.config -recurse | remove-item -recurse -force"
#          
#          #      - name: Publish the app 
#          #        run: |
#          #          Start-Process powershell -Verb RunAs -ArgumentList "dotnet publish"
#          #          Start-Sleep -Seconds 10
#
#      - name: Copy the files to the website folder
#        run: Start-Process powershell -Verb RunAs -ArgumentList "Copy-Item -Path bin\Release\net6.0\* -Destination C:\inetpub\wwwroot\equip-service\ -Recurse -Force -Exclude web.config"
#
#      - name: Start the website
#        run: Start-Process powershell -Verb RunAs -ArgumentList "Start-WebAppPool -Name SmWebApiPool" 
